// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjE4jydbJzcaM_kRktR9oe4sUWaJY8iGk',
    appId: '1:1022472538599:web:fc779e00991c73e7665542',
    messagingSenderId: '1022472538599',
    projectId: 'fooddelievery-d2502',
    authDomain: 'fooddelievery-d2502.firebaseapp.com',
    storageBucket: 'fooddelievery-d2502.appspot.com',
    measurementId: 'G-H4BQCGM80F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD4sXJ1F9YNTp0WkjSZiALbeSFTd_mzzI',
    appId: '1:1022472538599:android:1cd69566d3b6dd39665542',
    messagingSenderId: '1022472538599',
    projectId: 'fooddelievery-d2502',
    storageBucket: 'fooddelievery-d2502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_iTFaNgvhclpkNKpXFisxN3sPH8HxnQ',
    appId: '1:1022472538599:ios:f4259f980ac29a4f665542',
    messagingSenderId: '1022472538599',
    projectId: 'fooddelievery-d2502',
    storageBucket: 'fooddelievery-d2502.appspot.com',
    iosBundleId: 'com.example.foodDelieveryappPrerna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_iTFaNgvhclpkNKpXFisxN3sPH8HxnQ',
    appId: '1:1022472538599:ios:91a84859b5baffe3665542',
    messagingSenderId: '1022472538599',
    projectId: 'fooddelievery-d2502',
    storageBucket: 'fooddelievery-d2502.appspot.com',
    iosBundleId: 'com.example.foodDelieveryappPrerna.RunnerTests',
  );
}
